insert into questions (vertical, question) values ('Aquamarine', 'Clotrimazole');
insert into questions (vertical, question) values ('Pink', 'clonidine hydrochloride');
insert into questions (vertical, question) values ('Crimson', 'Acetaminophen, Chlorpheniramine maleate and Dextromethorphan HBr');
insert into questions (vertical, question) values ('Yellow', 'RIFAXIMIN');
insert into questions (vertical, question) values ('Blue', 'Dextrose Monohydrate, Sodium Chloride, Calcium Chloride, Magnesium Chloride, Sodium Lactate');
insert into questions (vertical, question) values ('Puce', 'Oxygen');
insert into questions (vertical, question) values ('Maroon', 'Levetiracetam');
insert into questions (vertical, question) values ('Orange', 'BENZONATATE');
insert into questions (vertical, question) values ('Mauv', 'Gabapentin');
insert into questions (vertical, question) values ('Goldenrod', 'benzocaine');
insert into questions (vertical, question) values ('Mauv', 'Bupivacaine Hydrochloride');
insert into questions (vertical, question) values ('Green', 'Titanium Dioxide and Zinc Oxide');
insert into questions (vertical, question) values ('Yellow', 'Quetiapine fumarate');
insert into questions (vertical, question) values ('Green', 'fluticasone propionate and salmeterol');
insert into questions (vertical, question) values ('Indigo', 'Etodolac');
insert into questions (vertical, question) values ('Maroon', 'Magnesium hydroxide');
insert into questions (vertical, question) values ('Turquoise', 'ALCOHOL');
insert into questions (vertical, question) values ('Fuscia', 'GLYCERIN');
insert into questions (vertical, question) values ('Teal', 'Avobenzone , Octinoxate and Octisalate');
insert into questions (vertical, question) values ('Maroon', 'petrolatum');
insert into responses (question_id, response) values (5, 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.');
insert into responses (question_id, response) values (8, 'Donec posuere metus vitae ipsum.');
insert into responses (question_id, response) values (3, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.');
insert into responses (question_id, response) values (4, 'Donec ut mauris eget massa tempor convallis.');
insert into responses (question_id, response) values (11, 'Curabitur convallis.');
insert into responses (question_id, response) values (10, 'Maecenas tincidunt lacus at velit.');
insert into responses (question_id, response) values (19, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.');
insert into responses (question_id, response) values (15, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into responses (question_id, response) values (1, 'Nunc nisl.');
insert into responses (question_id, response) values ( 4, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into responses (question_id, response) values ( 7, 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into responses (question_id, response) values ( 20, 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into responses (question_id, response) values ( 1, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into responses (question_id, response) values ( 1, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.');
insert into responses (question_id, response) values ( 9, 'Proin at turpis a pede posuere nonummy.');
insert into responses (question_id, response) values ( 9, 'Nulla suscipit ligula in lacus.');
insert into responses (question_id, response) values ( 11, 'Suspendisse potenti.');
insert into responses (question_id, response) values ( 2, 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.');
insert into responses (question_id, response) values ( 16, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
insert into responses (question_id, response) values ( 5, 'Duis bibendum.');
insert into responses (question_id, response) values ( 6, 'Etiam vel augue. Vestibulum rutrum rutrum neque.');
insert into responses (question_id, response) values ( 1, 'Suspendisse potenti.');
insert into responses (question_id, response) values ( 20, 'Vivamus vel nulla eget eros elementum pellentesque.');
insert into responses (question_id, response) values ( 10, 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into responses (question_id, response) values ( 15, 'Nulla nisl. Nunc nisl.');
insert into responses (question_id, response) values ( 10, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.');
insert into responses (question_id, response) values ( 5, 'Vestibulum ac est lacinia nisi venenatis tristique.');
insert into responses (question_id, response) values ( 20, 'Cras non velit nec nisi vulputate nonummy.');
insert into responses (question_id, response) values ( 20, 'Aliquam non mauris.');
insert into responses (question_id, response) values ( 20, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into responses (question_id, response) values ( 10, 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.');
insert into responses (question_id, response) values ( 3, 'Phasellus sit amet erat. Nulla tempus.');
insert into responses (question_id, response) values ( 12, 'Suspendisse potenti.');
insert into responses (question_id, response) values ( 16, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.');
insert into responses (question_id, response) values ( 14, 'Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into responses (question_id, response) values ( 11, 'Donec dapibus.');
insert into responses (question_id, response) values ( 5, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.');
insert into responses (question_id, response) values ( 16, 'Nulla tellus. In sagittis dui vel nisl.');
insert into responses (question_id, response) values ( 19, 'Quisque ut erat. Curabitur gravida nisi at nibh.');
insert into responses (question_id, response) values ( 13, 'Etiam vel augue. Vestibulum rutrum rutrum neque.');
insert into responses (question_id, response) values ( 15, 'Suspendisse potenti.');
insert into responses (question_id, response) values ( 19, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');
insert into responses (question_id, response) values ( 12, 'Curabitur at ipsum ac tellus semper interdum.');
insert into responses (question_id, response) values ( 19, 'Vivamus vel nulla eget eros elementum pellentesque.');
insert into responses (question_id, response) values ( 18, 'Duis bibendum.');
insert into responses (question_id, response) values ( 4, 'Nulla nisl. Nunc nisl.');
insert into responses (question_id, response) values ( 6, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into responses (question_id, response) values ( 17, 'Donec dapibus. Duis at velit eu est congue elementum.');
insert into responses (question_id, response) values ( 4, 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into responses (question_id, response) values ( 14, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');